spritesConfig  = {
    "spriteSheets": [{
        "id": "grass",
        "file": "grass-tiles.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 1,
            "x": 0,
            "y": 64,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 2,
            "x": 0,
            "y": 128,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 3,
            "x": 0,
            "y": 192,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 4,
            "x": 0,
            "y": 256,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 5,
            "x": 0,
            "y": 320,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 6,
            "x": 0,
            "y": 384,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 7,
            "x": 0,
            "y": 448,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 8,
            "x": 0,
            "y": 512,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 9,
            "x": 0,
            "y": 576,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 10,
            "x": 0,
            "y": 640,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 11,
            "x": 0,
            "y": 704,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 12,
            "x": 0,
            "y": 768,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 13,
            "x": 0,
            "y": 832,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 14,
            "x": 0,
            "y": 896,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }, {
            "variation": 15,
            "x": 0,
            "y": 960,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }]
    }, {
        "id": "water",
        "file": "water.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 64,
            "height": 64,
            "frames": 2,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }]
    }, {
        "id": "sand",
        "file": "sand.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }]
    }, {
        "id": "wood_plank",
        "file": "wood-plank.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 0
        }]
    }, {
        "id": "stone_wall_vertical_left",
        "file": "stone-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 128,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 1
        }, {
            "variation": 1,
            "x": 0,
            "y": 192,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 1
        }, {
            "variation": 2,
            "x": 0,
            "y": 256,
            "width": 64,
            "height": 128,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -64,
            "zIndex": 1
        }]
    }, {
        "id": "stone_wall_vertical_right",
        "file": "stone-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 384,
            "y": 128,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 1
        }, {
            "variation": 1,
            "x": 384,
            "y": 192,
            "width": 64,
            "height": 64,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 1
        }, {
            "variation": 2,
            "x": 384,
            "y": 256,
            "width": 64,
            "height": 128,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 1
        }]
    }, {
        "id": "stone_wall_horizontal_top",
        "file": "stone-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 64,
            "y": 0,
            "width": 64,
            "height": 128,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -64,
            "zIndex": 1
        }, {
            "variation": 1,
            "x": 128,
            "y": 0,
            "width": 128,
            "height": 128,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -64,
            "zIndex": 1
        }, {
            "variation": 2,
            "x": 256,
            "y": 0,
            "width": 64,
            "height": 128,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -64,
            "zIndex": 1
        }]
    }, {
        "id": "stone_wall_horizontal_bottom",
        "file": "stone-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 64,
            "y": 384,
            "width": 64,
            "height": 128,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -64,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 128,
            "y": 384,
            "width": 64,
            "height": 128,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -64,
            "zIndex": 3
        }, {
            "variation": 2,
            "x": 256,
            "y": 384,
            "width": 64,
            "height": 128,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -64,
            "zIndex": 3
        }]
    }, {
        "id": "wooden_wall_vertical_left",
        "file": "wooden-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 288,
            "width": 96,
            "height": 96,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -9,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 0,
            "y": 384,
            "width": 96,
            "height": 192,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -96,
            "zIndex": 3
        }, {
            "variation": 2,
            "x": 0,
            "y": 672,
            "width": 96,
            "height": 96,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -96,
            "zIndex": 3
        }]
    }, {
        "id": "wooden_wall_vertical_right",
        "file": "wooden-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 576,
            "y": 288,
            "width": 96,
            "height": 96,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -27,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 576,
            "y": 384,
            "width": 96,
            "height": 192,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 576,
            "y": 672,
            "width": 96,
            "height": 96,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 3
        }]
    }, {
        "id": "wooden_wall_horizontal_top",
        "file": "wooden-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 96,
            "y": 0,
            "width": 96,
            "height": 288,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -219,
            "zIndex": 1
        }, {
            "variation": 1,
            "x": 192,
            "y": 0,
            "width": 96,
            "height": 288,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -205,
            "zIndex": 1
        }, {
            "variation": 2,
            "x": 384,
            "y": 0,
            "width": 96,
            "height": 288,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -205,
            "zIndex": 1
        }]
     }, {
        "id": "wooden_wall_horizontal_bottom",
        "file": "wooden-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 96,
            "y": 768,
            "width": 96,
            "height": 288,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -96,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 192,
            "y": 768,
            "width": 96,
            "height": 288,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -96,
            "zIndex": 3
        }, {
            "variation": 2,
            "x": 384,
            "y": 768,
            "width": 96,
            "height": 288,
            "frames": 1,
            "offsetX": 0,
            "offsetY": -96,
            "zIndex": 3
        }]
    }, {
        "id": "tree",
        "file": "tree.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 288,
            "height": 336,
            "frames": 1,
            "offsetX": -60,
            "offsetY": -232,
            "zIndex": 2
        }]
    }, {
        "id": "chest",
        "file": "chest.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 28,
            "frames": 1,
            "offsetX": 0,
            "offsetY": 0,
            "zIndex": 1
        }]
    }]
}