// [wall_type] [vertical/horizontal] [position on the grid square] [sprite variation]
module.exports = [
    {
        id: 1,
        name: 'wooden_wall_vertical_left',
        collision: 2
    }, {
        id: 2,
        name: 'wooden_wall_vertical_right',
        collision: 1
    }, {
        id: 3,
        name: 'wooden_wall_horizontal_top',
        collision: 4
    }, {
        id: 4,
        name: 'wooden_wall_horizontal_bottom',
        collision: 8
    }, {
        id: 5,
        name: 'wooden_fence_vertical_left',
        collision: 2
    }, {
        id: 6,
        name: 'wooden_fence_vertical_right',
        collision: 1
    }, {
        id: 7,
        name: 'wooden_fence_horizontal_top',
        collision: 4
    }, {
        id: 8,
        name: 'wooden_fence_horizontal_bottom',
        collision: 8
    }, {
        id: 9,
        name: 'grass',
        collision: 0
    }, {
        id: 10,
        name: 'tree',
        collision: 8
    }, {
        id: 11,
        name: 'golden_chest',
        collision: 15
    }, {
        id: 12,
        name: 'wooden_chest',
        collision: 4
    }, {
        id: 13,
        name: 'daisy_flower_pot',
        collision: 4
    }, {
        id: 14,
        name: 'barrel',
        collision: 4
    }, {
        id: 15,
        name: 'anvil',
        collision: 8
    }, {
        id: 16,
        name: 'wooden_table',
        collision: 15
    }, {
        id: 17,
        name: 'bear_carpet',
        collision: 0
    }, {
        id: 18,
        name: 'armor_rack',
        collision: 4
    }, {
        id: 19,
        name: 'wooden_door_horizontal_top',
        collision: 4
    }
];
