module.exports = {
    "spriteSheets": [{
        "id": "grass_tile",
        "file": "grass-tiles.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 1,
            "x": 0,
            "y": 32,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 2,
            "x": 0,
            "y": 64,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 3,
            "x": 0,
            "y": 96,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 4,
            "x": 0,
            "y": 128,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 5,
            "x": 0,
            "y": 160,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 6,
            "x": 0,
            "y": 192,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 7,
            "x": 0,
            "y": 224,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 8,
            "x": 0,
            "y": 256,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 9,
            "x": 0,
            "y": 288,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 10,
            "x": 0,
            "y": 320,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 11,
            "x": 0,
            "y": 352,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 12,
            "x": 0,
            "y": 384,
            "width": 32,
            "height": 32,
            "frames": 4,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 13,
            "x": 0,
            "y": 416,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 14,
            "x": 0,
            "y": 448,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 15,
            "x": 0,
            "y": 480,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 16,
            "x": 0,
            "y": 512,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 17,
            "x": 0,
            "y": 544,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 18,
            "x": 0,
            "y": 576,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 19,
            "x": 0,
            "y": 609,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 20,
            "x": 0,
            "y": 640,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 21,
            "x": 0,
            "y": 672,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 22,
            "x": 0,
            "y": 704,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 23,
            "x": 0,
            "y": 736,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 24,
            "x": 0,
            "y": 768,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 25,
            "x": 0,
            "y": 800,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 26,
            "x": 0,
            "y": 832,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 27,
            "x": 0,
            "y": 864,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 28,
            "x": 0,
            "y": 896,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 29,
            "x": 0,
            "y": 928,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 30,
            "x": 0,
            "y": 960,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 31,
            "x": 0,
            "y": 992,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 32,
            "x": 0,
            "y": 1024,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 33,
            "x": 0,
            "y": 1056,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 34,
            "x": 0,
            "y": 1088,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 35,
            "x": 0,
            "y": 1120,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 36,
            "x": 0,
            "y": 1152,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 37,
            "x": 0,
            "y": 1184,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 38,
            "x": 0,
            "y": 1216,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }]
    }, {
        "id": "water",
        "file": "water.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }]
    }, {
        "id": "earth_tile",
        "file": "earth-tiles.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 1,
            "x": 0,
            "y": 32,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 2,
            "x": 0,
            "y": 64,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 3,
            "x": 0,
            "y": 96,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 4,
            "x": 0,
            "y": 128,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 5,
            "x": 0,
            "y": 160,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 6,
            "x": 0,
            "y": 192,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 7,
            "x": 0,
            "y": 224,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 8,
            "x": 0,
            "y": 256,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 9,
            "x": 0,
            "y": 288,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 10,
            "x": 0,
            "y": 320,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 11,
            "x": 0,
            "y": 352,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 12,
            "x": 0,
            "y": 384,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 13,
            "x": 0,
            "y": 416,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 14,
            "x": 0,
            "y": 448,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 15,
            "x": 0,
            "y": 480,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 16,
            "x": 0,
            "y": 512,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 17,
            "x": 0,
            "y": 544,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 18,
            "x": 0,
            "y": 576,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 19,
            "x": 0,
            "y": 608,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 20,
            "x": 0,
            "y": 640,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }]
    }, {
        "id": "wood_plank",
        "file": "wood-plank.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 1,
            "x": 0,
            "y": 32,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 2,
            "x": 0,
            "y": 64,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 3,
            "x": 0,
            "y": 96,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 4,
            "x": 0,
            "y": 128,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 5,
            "x": 0,
            "y": 160,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 6,
            "x": 0,
            "y": 192,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 7,
            "x": 0,
            "y": 224,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 8,
            "x": 0,
            "y": 256,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 9,
            "x": 0,
            "y": 288,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 10,
            "x": 0,
            "y": 320,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 11,
            "x": 0,
            "y": 352,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 12,
            "x": 0,
            "y": 384,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 13,
            "x": 0,
            "y": 416,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 14,
            "x": 0,
            "y": 448,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 15,
            "x": 0,
            "y": 480,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 16,
            "x": 0,
            "y": 512,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 17,
            "x": 0,
            "y": 544,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }, {
            "variation": 18,
            "x": 0,
            "y": 576,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 0
        }]
    }, {
        "id": "wooden_wall_vertical_left",
        "file": "wooden-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 80,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 0,
            "y": 96,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 2,
            "x": 0,
            "y": 128,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 3,
            "x": 0,
            "y": 160,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 4,
            "x": 0,
            "y": 224,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 5,
            "x": 0,
            "y": 256,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 6,
            "x": 0,
            "y": 288,
            "width": 32,
            "height": 35,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }]
    }, {
        "id": "wooden_wall_vertical_right",
        "file": "wooden-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 224,
            "y": 0,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 80,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 224,
            "y": 96,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 2,
            "x": 224,
            "y": 128,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 3,
            "x": 224,
            "y": 160,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 4,
            "x": 224,
            "y": 224,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 5,
            "x": 224,
            "y": 256,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 6,
            "x": 224,
            "y": 288,
            "width": 32,
            "height": 35,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }]
    }, {
        "id": "wooden_wall_horizontal_top",
        "file": "wooden-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 32,
            "y": 0,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 80,
            "zIndex": 1
        }, {
            "variation": 1,
            "x": 64,
            "y": 0,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 80,
            "zIndex": 1
        }, {
            "variation": 2,
            "x": 96,
            "y": 0,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 80,
            "zIndex": 1
        }, {
            "variation": 3,
            "x": 128,
            "y": 0,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 80,
            "zIndex": 1
        }, {
            "variation": 4,
            "x": 192,
            "y": 0,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 80,
            "zIndex": 1
        }, {
            "variation": 5,
            "x": 160,
            "y": 0,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 80,
            "zIndex": 1
        }]
     }, {
        "id": "wooden_wall_horizontal_bottom",
        "file": "wooden-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 32,
            "y": 256,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 48,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 64,
            "y": 256,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 48,
            "zIndex": 3
        }, {
            "variation": 2,
            "x": 96,
            "y": 256,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 48,
            "zIndex": 3
        }, {
            "variation": 3,
            "x": 128,
            "y": 256,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 48,
            "zIndex": 3
        }, {
            "variation": 4,
            "x": 192,
            "y": 256,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 48,
            "zIndex": 3
        }, {
            "variation": 5,
            "x": 160,
            "y": 256,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 48,
            "zIndex": 3
        }]
    }, {
        "id": "wooden_door_horizontal_top",
        "file": "wooden-wall.png",
        "sprites": [{
            "variation": 0,
            "x": 64,
            "y": 96,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 80,
            "zIndex": 1
        }, {
            "variation": 1,
            "x": 160,
            "y": 96,
            "width": 32,
            "height": 96,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 80,
            "zIndex": 1
        }]
    }, {
        "id": "wooden_fence_vertical_left",
        "file": "wooden-fence.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 64,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 48,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 0,
            "y": 64,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 2,
            "x": 0,
            "y": 96,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }]
    }, {
        "id": "wooden_fence_vertical_right",
        "file": "wooden-fence.png",
        "sprites": [{
            "variation": 0,
            "x": 128,
            "y": 0,
            "width": 32,
            "height": 64,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 48,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 128,
            "y": 64,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 2,
            "x": 128,
            "y": 96,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }]
    }, {
        "id": "wooden_fence_horizontal_top",
        "file": "wooden-fence.png",
        "sprites": [{
            "variation": 0,
            "x": 32,
            "y": 0,
            "width": 32,
            "height": 64,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 48,
            "zIndex": 1
        }, {
            "variation": 1,
            "x": 64,
            "y": 0,
            "width": 32,
            "height": 64,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 48,
            "zIndex": 1
        }, {
            "variation": 2,
            "x": 96,
            "y": 0,
            "width": 32,
            "height": 64,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 48,
            "zIndex": 1
        }]
    }, {
        "id": "wooden_fence_horizontal_bottom",
        "file": "wooden-fence.png",
        "sprites": [{
            "variation": 0,
            "x": 32,
            "y": 96,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 64,
            "y": 96,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }, {
            "variation": 2,
            "x": 96,
            "y": 96,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }]
    }, {
        "id": "grass",
        "file": "grass.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 36,
            "height": 36,
            "frames": 1,
            "offsetX": 18,
            "offsetY": 18,
            "zIndex": 1
        }, {
            "variation": 1,
            "x": 0,
            "y": 36,
            "width": 36,
            "height": 36,
            "frames": 1,
            "offsetX": 18,
            "offsetY": 18,
            "zIndex": 1
        }, {
            "variation": 2,
            "x": 0,
            "y": 72,
            "width": 36,
            "height": 36,
            "frames": 1,
            "offsetX": 18,
            "offsetY": 18,
            "zIndex": 1
        }, {
            "variation": 3,
            "x": 0,
            "y": 108,
            "width": 36,
            "height": 36,
            "frames": 1,
            "offsetX": 18,
            "offsetY": 18,
            "zIndex": 1
        }]
    }, {
        "id": "tree",
        "file": "tree.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 96,
            "height": 112,
            "frames": 1,
            "offsetX": 49,
            "offsetY": 90,
            "zIndex": 2
        }]
    }, {
        "id": "golden_chest",
        "file": "golden-chest.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 28,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 28,
            "zIndex": 1
        }]
    }, {
        "id": "wooden_chest",
        "file": "wooden-chest.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 28,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 28,
            "zIndex": 1
        }]
    }, {
        "id": "daisy_flower_pot",
        "file": "daisy-flower-pot.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 30,
            "zIndex": 1
        }]
    }, {
        "id": "barrel",
        "file": "barrel.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 48,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 46,
            "zIndex": 1
        }]
    }, {
        "id": "anvil",
        "file": "anvil.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 3
        }]
    }, {
        "id": "wooden_table",
        "file": "wooden-table.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 42,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 26,
            "zIndex": 3
        }, {
            "variation": 1,
            "x": 0,
            "y": 32,
            "width": 42,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 16,
            "zIndex": 1
        }]
    }, {
        "id": "bear_carpet",
        "file": "bear-carpet.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 38,
            "height": 38,
            "frames": 1,
            "offsetX": 19,
            "offsetY": 24,
            "zIndex": 1
        }]
    }, {
        "id": "armor_rack",
        "file": "armor-rack.png",
        "sprites": [{
            "variation": 0,
            "x": 0,
            "y": 0,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 31,
            "zIndex": 1
        }, {
            "variation": 1,
            "x": 0,
            "y": 32,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 31,
            "zIndex": 1
        }, {
            "variation": 2,
            "x": 0,
            "y": 64,
            "width": 32,
            "height": 32,
            "frames": 1,
            "offsetX": 16,
            "offsetY": 31,
            "zIndex": 1
        }]
    }]
}